### PR TITLE
Adds basic utilities for Born lensing

### PR DESCRIPTION
**Pull request by EiffL**
This PR adds a few utility functions that enable lensing through a given simualtion

A demo notebook is available [here](https://github.com/DifferentiableUniverseInitiative/JaxPM/blob/u/EiffL/lensing/notebooks/lensing_demo.ipynb)

### CODE REVIEW

**Review by EiffL — COMMENTED** [review]
lgtm, but missing tests

**Comment by EiffL** [comment]
@dlanzieri  can you take a quick look at this?

**Review by dlanzieri — COMMENTED** [review]
@EiffL This looks fantastic! 
Everything in the codes seems ok to me, however, there is something I didn't understand in the [notebook](https://github.com/DifferentiableUniverseInitiative/JaxPM/blob/0f6fb399662baebbe3027b326b5fc5b82f0c939f/notebooks/lensing_demo.ipynb):
image
This seems slightly different from what I'm used to seeing. Can you explain to me what's going on?

**Comment by EiffL** [comment]
hum, no this is what it's supposed to look like, you are looking at the convergence map for a source plane going further and further away. At first the source plane is just in front of us, so we only see something very blurry, but as it moves further and further away you start to see more stuff on small scale because you are looking at structures further away from us

**Pull request merged**
